// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhmfA9JrcuNeTNKFfvzFVwkVMLvFBaVOU',
    appId: '1:161706603662:android:10c7945d1b9cf2e5bfc5df',
    messagingSenderId: '161706603662',
    projectId: 'project2-69f47',
    storageBucket: 'project2-69f47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgkDzcLgURKx3RmGwZpF6aNUehVjKFHzM',
    appId: '1:161706603662:ios:e3b99db1b0afebbebfc5df',
    messagingSenderId: '161706603662',
    projectId: 'project2-69f47',
    storageBucket: 'project2-69f47.appspot.com',
    androidClientId:
        '161706603662-mbo9aisbjloh6q33t4got9qfo2qs48a0.apps.googleusercontent.com',
    iosClientId:
        '161706603662-9a9lfa9a63jks4t0sk5k5m48qeo90kq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
